# Generated by Django 5.0.1 on 2024-02-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tag_post_alter_tag_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='review',
        ),
        migrations.AddField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
