# Generated by Django 5.0.1 on 2024-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tag_lists_remove_tag_post_remove_tag_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country tag'),
        ),
    ]
