# Generated by Django 5.0.1 on 2024-02-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_list_comments_alter_list_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='list',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='list',
            name='review',
        ),
        migrations.AddField(
            model_name='list',
            name='comments',
            field=models.ManyToManyField(blank=True, to='api.comments'),
        ),
        migrations.AddField(
            model_name='list',
            name='posts',
            field=models.ManyToManyField(blank=True, to='api.post'),
        ),
        migrations.AddField(
            model_name='list',
            name='review',
            field=models.ManyToManyField(blank=True, to='api.review'),
        ),
    ]
