# Generated by Django 5.0.1 on 2024-04-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_chat_to_user_alter_chat_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.TextField(default='Li', verbose_name='review title'),
            preserve_default=False,
        ),
    ]
